version: '3.6'

services:
  node:
    image: node:15.2.1
    ports:
      - '80:8080'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    working_dir: /app
    command: /bin/sh -c "npm run serve"
